nombre_usuario=input("INTRODUCE tu nombre ")
print ("Nombre: ",nombre_usuario)
apellido_usuario=input("cual es tu apellido? ")
print("apellido: ", apellido_usuario)
num_usuario=input("cual es tu # de usuario? ")
print("# de empleado: ",num_usuario)
puesto_usuario=input("cual es tu Puesto? ")
print("puesto: ",puesto_usuario)
edad_usuario=int(input("cual es tu edad? "))
print("edad: ",edad_usuario)
antiguedad=float(input("cual es tu antiguedad? "))
print("antiguedad: ",antiguedad, " años")
sindicalizado=bool(input("¿eres sindicalizado? 0 No, 1 Si ? "))
print("sindicalizado = ",sindicalizado)